### ISSUE TITLE
Implement HTTPRequest using raw Socket

### ISSUE THREAD

**Issue by andrewburnheimer** [andrewburnheimer/EmbUI#7]
Currently can not communicate directly with SFP devices - we must always communicate through an SSH tunnel. Resolving this issue will work-around the current lack of support for HTTP 1.1 `Expect: 100-continue` headers and behavior in the SFP API.

**Comment by edwin-mejia** [comment]
GETs and PUTs all using Socket now, no issue with packet splitting.
